name: Continuous Integration

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ 3.7, 3.8, 3.9 ]
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2
      with:
        submodules: "true"
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -e .
        pip install -r dev_requirements.txt
    - name: Run tests
      run: |
        pytest tests
